### ISSUE TITLE
counter_clockwise arc error

### ISSUE THREAD

**Issue by windtail** [a-e-k/canvas_ity#8]
Hi,

The following code will draw nothing, is this expected behavior? i am new to canvas. The code is taken from https://playcode.io/canvas

```c++
arc(75, 75, 50, 0, PI * 2, true)
```

i think the following code maybe need some adjustment
```c++
    static float const tau = 6.28318531f;
    float winding = counter_clockwise ? -1.0f : 1.0f;
    float from = fmodf( start_angle, tau );
    float span = fmodf( end_angle, tau ) - from;
    if ( ( end_angle - start_angle ) * winding >= tau )  // <-----
        span = tau * winding;
    else if ( span * winding < 0.0f )
        span += tau * winding;
```

Thanks!

**Comment by a-e-k** [comment]
Hi.  The [controlling description in the spec](https://www.w3.org/TR/2015/REC-2dcontext-20151119/#dom-context-2d-arc) is this:

> Consider a circle that has its origin at (x, y), and that has radius radius. The points at startAngle and endAngle this circle's circumference, measured in radians clockwise from the positive x-axis, are the start and end points respectively.
>
> If the counterclockwise argument false and endAngle-startAngle is equal to or greater than 2π, or if the counterclockwise argument is true and startAngle-endAngle is equal to or greater than 2π, then the arc is the whole circumference of this circle.
>
> Otherwise, the arc is the path along the circumference of this circle from the start point to the end point, going anti-clockwise if the counterclockwise argument is true, and clockwise otherwise. Since the points are on the circle, as opposed to being simply angles from zero, the arc can never cover an angle greater than 2π radians. If the two points are the same, or if the radius is zero, then the arc is defined as being of zero length in both directions.

Here, the third paragraph applies since the counterclockwise argument is true and startAngle-endAngle is -2π (negative) and therefore not greater than or equal to 2π radians.  And in this case, the two points are the effectively same so the arc is zero length and disappears.

You can reproduce this in your [playcode link](https://playcode.io/canvas).  On my browser (Firefox 129.0.2 on Fedora 40), if I change the end angle by just a smidge:

```js
ctx.arc(75, 75, 50, 0, Math.PI * 2 - 0.0000001, true);
```

then the outer circle disappears.

For drawing a full circle using `arc()`, I recommend either adding a small epsilon value to the end angle if the counterclockwise argument is false:

```js
ctx.arc(75, 75, 50, 0, Math.PI * 2 + 1.0e-6, false);
```

or, if the counterclockwise argument is true, using a negative angle (such that it agrees with the direction of the counterclockwise flag)  with the and subtracting a small epsilon:

```js
ctx.arc(75, 75, 50, 0, Math.PI * -2 - 1.0e-6, false);
```

I.e., a magnitude of 2π and a bit with the sign agreeing with the direction flag.  This will robustly give you a full circle with both this library and with browser canvas implementations.

**Comment by windtail** [comment]
Thanks so much for your detailed explanation!
