### ISSUE TITLE
Using canvas_ity in a class based cpp library

### ISSUE THREAD

**Issue by Johnsel** [a-e-k/canvas_ity#9]
Hi!

We're trying to submodule your library in ngscopeclient/scopehal, as a replacement for cairo, but I am running into issues using it as part of a class with multiple functions. Could you be so kind as to provide an example in the repo? Or at least some basic code here where you show how/what we should keep a reference for the class property or to pass between methods? For performance reasons we can't stuff everything in one method, we've tried :') 

Would appreciate any response, and hopefully you can help us out and your library can be added to ngscopeclient. We'd love to finally get rid of cairo.....

Trying to keep a class property like:

```cpp
/**
	@brief A mask used for checking eye patterns
 */
class EyeMask
{
public:
	EyeMask();
	virtual ~EyeMask();

.....

	canvas_ity::canvas canvas;

};`

We're running into stuff like:

`cpp
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp: In constructor ‘EyeMask::EyeMask()’:
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:55:37: error: no matching function for call to ‘canvas_ity::canvas::canvas()’
[build]    55 |         , m_timebaseIsRelative(false)
[build]       |                                     ^
[build] In file included from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.h:39,
[build]                  from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/BERTInputChannel.h:34,
[build]                  from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/BERT.h:423,
[build]                  from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/scopehal.h:132,
[build]                  from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:36:
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/../canvas_ity/src/canvas_ity.hpp:1173:5: note: candidate: ‘canvas_ity::canvas::canvas(const canvas_ity::canvas&)’
[build]  1173 |     canvas( canvas const & );
[build]       |     ^~~~~~
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/../canvas_ity/src/canvas_ity.hpp:1173:5: note:   candidate expects 1 argument, 0 provided
[build] In file included from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:42:
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/../canvas_ity/src/canvas_ity.hpp:2607:1: note: candidate: ‘canvas_ity::canvas::canvas(int, int)’
[build]  2607 | canvas::canvas(
```

```cpp
[build]                  from /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:36:
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/../canvas_ity/src/canvas_ity.hpp:1174:13: note: declared private here
[build]  1174 |     canvas &operator=( canvas const & );
[build]       |             ^~~~~~~~
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:187:55: error: passing ‘const canvas_ity::canvas’ as ‘this’ argument discards qualifiers [-fpermissive]
[build]   187 |         this->canvas = canvas_ity::canvas(width,height); 
```

and

[](https://github.com/Johnsel/scopehal/commits/remove-cairo/)

**Comment by Johnsel** [comment]
[Please find some minimal reproduction code in the linked repository](https://github.com/Johnsel/canvas_ity_class_minimal_repro)
Let me know if you have any questions!

**Comment by a-e-k** [comment]
Hi John,

The issue here is that instances of the `canvas` class can be fairly heavyweight with respect to memory (most of that going to the internal frame buffer).  So to prevent passing accidentally it around by value, the copy constructor is private.  The error that you saw is intentional, to avoid misuse.

If you were just going create the canvas at a given size once in your class, and you know up front the size you need when your class is constructed, then you can construct the instance of the class in the constructor's initializer list since that constructs it in-place without copying.  E.g.:

```c++
#define CANVAS_ITY_IMPLEMENTATION
#include "canvas_ity.hpp"

class Example1
{
public:
    Example1( int width, int height )
        : example_canvas( width, height )
    {
    }

private:
    canvas_ity::canvas example_canvas;
};
```

However, it looks like you'd like to have the flexibility to create instances of whatever size you need on-the-fly, and to create and destroy those instances when that size changes?  In that case, I'd suggest using something like [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) to hold the instance within your class.  E.g.:

```c++
#include <memory>  // For std::unique_ptr
#include <cassert> // For assert

#define CANVAS_ITY_IMPLEMENTATION
#include "canvas_ity.hpp"

class Example2
{
public:
    void draw( int width, int height )
    {
        // Constructs a new canvas (destroys and replaces the old instance, if any)
        example_canvas = std::make_unique< canvas_ity::canvas >( width, height );
    }

    void more_drawing()
    {
        // Uses the last canvas instance constructed by draw()
        assert( example_canvas ); // (Programming error if it wasn't created first)
        example_canvas->fill_rectangle( 10.0f, 10.0f, 20.0f, 20.0f );
    }

private:
    std::unique_ptr< canvas_ity::canvas > example_canvas;
};
```

Using `unique_ptr` ensures that the old instance of the canvas will be automatically destroyed whenever you replace it.  It will also automatically destroy the current instance for you when your class gets destroyed (i.e., there is no need for a destructor in your class just to clean it up).

Do either of those options help?

**Comment by Johnsel** [comment]
Perfect, thank you. The latter should do what we need 👍

**Comment by Johnsel** [comment]
Actually, I'm noting I left out some details that do affect the issue further:

More specifically:

```cpp
	float CalculateHitRate(
		EyeWaveform* cap,
		size_t width,
		size_t height,
		float fullscalerange,
		float xscale,
		float xoff) const;
```


```cpp
scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp: In member function ‘float EyeMask::CalculateHitRate(EyeWaveform*, size_t, size_t, float, float, float) const’:
[build] /home/johnsimons/scopehal-apps_working_copy/lib/scopehal/EyeMask.cpp:186:72: error: passing ‘const std::unique_ptr<canvas_ity::canvas>’ as ‘this’ argument discards qualifiers [-fpermissive]
[build]   186 |         canvas = std::make_unique< canvas_ity::canvas >( width, height );
[build]       |                                                                        ^
```

It may already be clear to you but c++ is not a language I'm well versed in, and this codebase I'm also not very involved in. That said. I'd like to solve this issue.

I'll update the minimal repro and hopefully you can help me one more time :)

**Comment by Johnsel** [comment]
@a-e-k tag as I don't know if you monitor closed issues still :) sorry if you do

Note that this is the concernerning code and the .h defines the class. Just in case the way inheritance is set up will be the next issue: [https://github.com/Johnsel/scopehal/blob/9d8727602df589458bbebeda91c0987d9781e4e9/scopehal/EyeMask.cpp](https://github.com/Johnsel/scopehal/blob/9d8727602df589458bbebeda91c0987d9781e4e9/scopehal/EyeMask.cpp)

**Comment by a-e-k** [comment]
My personal preference for issues to is to lean towards closing quickly, but then be willing to reopen or file new tickets as needed.  So no worries.

It's a little hard to tell what's going on without seeing the full context here.  But I notice from the error message that it's alluding to discarding qualifiers and considering the the `std::unique_ptr<canvas_ity::canvas>` to be `const`-qualified:


```c++
error: passing ‘const std::unique_ptr<canvas_ity::canvas>’ as ‘this’ argument discards qualifiers
//              ^- (here)
```

That's going to be because the `CalculateHitRate()` member function is `const`-qualified:

```c++
float CalculateHitRate(
	EyeWaveform* cap,
	size_t width,
	size_t height,
	float fullscalerange,
	float xscale,
	float xoff) const;
//                  ^- (here)
```

That means that you're promising that this member function won't change or mutate any of the class's member variables.  Assuming from the error that `canvas` here is a member variable (and not just a local), then trying to assign to it is breaking that promise and will trigger a compile error like the one you saw.  Since you're wanting to assign to it, you'll should consider making `CalculateHitRate()` non-`const`.

(Just note that making something non-`const` can be viral.  Any other `const` member functions calling it may need to be made non-`const` as well.)
